### ISSUE TITLE
Windows Azure Active Directory API

### ISSUE THREAD

**Issue by florianrusch** [avinor/terraform-azurerm-kubernetes-azuread-integration#1]
I've also implemented this feature successfully in a terraform module.
But I didn't have this permission request and it also works.

You know what it does exactly?

https://github.com/avinor/terraform-azurerm-kubernetes-azuread-integration/blob/8699b4f10cc8d9d5cc26d829ca381be4df730620/main.tf#L20-L30

The [documentation](https://docs.microsoft.com/en-us/azure/aks/azure-ad-integration#create-the-server-application) also just shows the other tree permissions:
![image](https://user-images.githubusercontent.com/1724759/63920419-1bd2de00-ca41-11e9-877e-b1e3cef26ddd.png)

**Comment by tesharp** [comment]
While I was testing I tried to add this as some examples had that, but as you mention it is not in any documentation. Remove it from module as it is not required.

Thanks
